sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t mriedmann/humhub .
  - docker run -d --name humhub_db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=humhub mariadb:10.2
  - docker run -d --name humhub -p 127.0.0.1:80:80 -v /src/:/src/ --link humhub_db:db mriedmann/humhub
  - sleep 10
  - docker ps -a
  - docker exec humhub /bin/sh -c "cp -r /usr/src/humhub /src/"

script:
  - cd /src/humhub/protected/vendor/bin
  - ls -l
  - phantomjs