sudo: required

language: php

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a

script:
  - sleep 60
  - curl http://localhost/ -L --fail -s | grep '<form id="account-login-form" action="/user/auth/login" method="post">' -q