sudo: required

language: php

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - sleep 60
  - docker ps -a

script:
  - curl http://localhost/ -L --fail -s | grep 'Sign in</button>' -q